services:
  php-apache:
    image: php:8.2-apache
    container_name: php82_optimy
    ports:
      - '8001:80'
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    build:
      context: .
      dockerfile: Dockerfile


  database:
    image: mysql:8.0
    container_name: test_db_optimy
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assignment_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - '3308:3306'
    volumes:
      - .:/docker-entrypoint-initdb.d

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80









